apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest #creating a container from this image, with empty data. server name:"localhost,1433"
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        - name: MSSQL_DATA_DIR
          value: /var/opt/mssql/data
        - name: MSSQL_LOG_DIR
          value: /var/opt/mssql/log
          
        volumeMounts:
        - name: mssql-base-volume
          mountPath: /var/opt/mssql
        - name: mssql-log-volume
          mountPath: /var/opt/mssql/log
        - name: mssql-data-volume
          mountPath: /var/opt/mssql/data
      volumes:
      - name: mssql-base-volume
        persistentVolumeClaim:
          claimName: mssql-base-volume
      - name: mssql-data-volume
        persistentVolumeClaim:
          claimName: mssql-data-volume
      - name: mssql-log-volume
        persistentVolumeClaim:
          claimName: mssql-log-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-clusterip
labels:
  app: mssql
spec:
  type: ClusterIP
  selector:
    app: mssql
  ports:
    - port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-loadbalancer
labels:
  app: mssql
spec:
  type: LoadBalancer
  selector:
    app: mssql
  ports:
    - port: 1433
      targetPort: 1433