apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade # run the Job before the upgrade/install the application
    "helm.sh/hook-weight": "-1" #define in which order helm should create resources
    "helm.sh/hook-delete-policy": hook-succeeded # automatically delete  the Job if it succeeds
spec:
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: db-migrate
    spec: 
        restartPolicy: Never
        containers:
          - name: db-migrate
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }} #build a dedicated docker image to run the migrations
            command: ["dotnet"]
            args: ["TestApp.Cli.dll", "migrate-database"]