apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-mssql-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-mssql-deployment
  labels:
    app: bookmssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmssql
  template:
    metadata:
      labels:
        app: bookmssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest #creating a container from this image, with empty data. server name:"localhost,1444"
        ports:
        - containerPort: 1444
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_TCP_PORT
          value: "1444"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: book-secret
              key: ConnectionStrings__SA_Password      
        volumeMounts:  
        - name: book-mssql
          mountPath: /var/opt/mssql/bookdata
      volumes:     
      - name: book-mssql
        persistentVolumeClaim:
          claimName: book-mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: book-mssql-clusterip
spec:
  type: ClusterIP
  selector:
    app: bookmssql
  ports:
    - port: 1444
      targetPort: 1444
---
apiVersion: v1
kind: Service
metadata:
  name: book-mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: bookmssql
  ports:
    - port: 1444
      targetPort: 1444