apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: books.co.il
    http:
      paths:
      - pathType: Prefix
        path: /api/books
        backend:
          service:
            name: book-api-clusterip
            port:
              number: 80
  - host: orders.co.il
    http:
      paths:
      - pathType: Prefix
        path: /api/orders
        backend:
          service:
            name: order-api-clusterip
            port:
              number: 80
      - pathType: Prefix
        path: /api/books
        backend:
          service:
            name: order-api-clusterip
            port:
              number: 80
