apiVersion: apps/v1
kind: Deployment
metadata:
   name: rabbitmq-deployment
   labels:
      app: rabbitmq
spec:
   replicas: 1
   selector:
      matchLabels:
         app: rabbitmq
   template:
      metadata:
         labels:
            app: rabbitmq
      spec:
         containers:
            - name:  rabbitmq
              image: rabbitmq:3.13.0-rc.2-management
              ports:
              - name: rabbitmq-management-port
                containerPort: 15672
              - name: rabbitmq-internal-port
                containerPort: 5672
              env:
              - name: RABBIT_HOST 
                value: "rabbitmq-cluster.rabbitmq.svc.cluster.local"
              - name: RABBIT_PORT
                value: "5672"
              - name: RABBITMQ_DEFAULT_USER
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-publisher
                    key: RABBIT_USERNAME
              - name: RABBITMQ_DEFAULT_PASS
                valueFrom:
                  secretKeyRef:
                    name: rabbitmq-publisher
                    key: RABBIT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
   name: rabbitmq-loadBalancer
spec:
   type: LoadBalancer
   ports:
      - name:  rabbitmq-management-port
        port: 15672
        targetPort: 15672   
      - name: rabbitmq-internal-port
        port: 5672
        targetPort: 5672    
   selector:
      app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
   name: rabbitmq-clusterip
spec:
   type: ClusterIP
   ports:
      - name: rabbitmq-management-port
        port: 15672
        targetPort: 15672    
      - name: rabbitmq-internal-port
        port: 5672
        targetPort: 15672       
   selector:
      app: rabbitmq